apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: axieanalytics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sam-lapointe/HomeLab
    path: apps/AxieAnalytics
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: axieanalytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true