apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: azuredns-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: slapointe@slapointe.com
    privateKeySecretRef:
      name: azuredns-issuer-private-key
    solvers:
    - dns01:
        azureDNS:
          clientID: 0fdbb3ff-a45e-4439-99b1-637405ac3031
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: e8be15f7-5f41-4d9c-9e4d-45171ac9c3ee
          tenantID: 624a1b1d-6f5e-4df5-bca3-6b3aebbdc02a
          resourceGroupName: DNS
          hostedZoneName: axieanalytics.com
          environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axieanalytics-com
  namespace: axieanalytics
spec:
  secretName: axieanalytics-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: axieanalytics.com
  dnsNames:
    - axieanalytics.com
    - "*.axieanalytics.com"
  issuerRef:
    name: azuredns-issuer
    kind: ClusterIssuer