apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: azuredns-issuer
spec:
  acme:
    ...
    solvers:
    - dns01:
        azureDNS:
          clientID: 0fdbb3ff-a45e-4439-99b1-637405ac3031
          clientSecretSecretRef:
          # The following is the secret created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: azuredns-config
            key: client-secret
          subscriptionID: e8be15f7-5f41-4d9c-9e4d-45171ac9c3ee
          tenantID: 624a1b1d-6f5e-4df5-bca3-6b3aebbdc02a
          resourceGroupName: DNS
          hostedZoneName: axieanalytics.com
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axieanalytics-com
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: axieanalytics-com-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  commonName: axieanalytics.com

  dnsNames:
    - axieanalytics.com
    - "*.axieanalytics.com"
  emailAddresses:
    - slapointe@slapointe.com

  issuerRef:
    name: azuredns-issuer
    kind: Issuer