apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.3.0
    helm:
      values: |
        ports:
          web:
            port: 8000
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            port: 8443
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik-internal
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.3.0
    helm:
      values: |
        ports:
          web:
            port: 8000
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            port: 8443
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik-external
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: networking
spec:
  type: LoadBalancer
  selector:
    app: traefik-internal
  ports:
    - name: web
      port: 8000
      targetPort: 8000
    - name: websecure
      port: 8443
      targetPort: 8443
  loadBalancerIP: 192.168.100.240
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: networking
spec:
  type: LoadBalancer
  selector:
    app: traefik-internal
  ports:
    - name: web
      port: 8000
      targetPort: 8000
    - name: websecure
      port: 8443
      targetPort: 8443
  loadBalancerIP: 192.168.100.241