apiVersion: apps/v1
kind: Deployment
metadata:
  name: axieanalytics-postgresql
  namespace: axieanalytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axieanalytics-postgresql
  template:
    metadata:
      labels: 
        app: axieanalytics-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17.5
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_ADMIN_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_ADMIN_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_DATABASE
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        - name: liquibase
          image: samlapointe01/axie-analytics:database-401
          command:
            - sh
            - -c
            - |
              export LIQUIBASE_URL="jdbc:postgresql://$PG_HOST:$PG_PORT/$PG_DATABASE" && \
              until pg_isready -h $PG_HOST -p $PG_PORT; do sleep 2; done && \
              liquibase --defaultsFile=liquibase.properties update
          env:
            - name: PG_HOST
              value: localhost
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_PORT
            - name: LIQUIBASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_ADMIN_USERNAME
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_ADMIN_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_DATABASE

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: axieanalytics-postgresql-pvc
      restartPolicy: Always