apiVersion: apps/v1
kind: Deployment
metadata:
  name: axieanalytics-postgresql
  namespace: axieanalytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axieanalytics-postgresql
  template:
    metadata:
      labels: 
        app: axieanalytics-postgresql
    spec:
      # initContainers:
      #   - name: copy-pg-hba
      #     image: busybox
      #     command:
      #       - sh
      #       - -c
      #       - |
      #         echo "Contents of /var/lib/postgresql/data:"
      #         ls -la /var/lib/postgresql/data/
      #         echo "Checking for base directory..."
      #         if [ -d /var/lib/postgresql/data/base ]; then
      #           echo "Database exists, copying pg_hba.conf..."
      #           cp /config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
      #           echo "pg_hba.conf copied successfully"
      #         else
      #           echo "Database not initialized yet, base directory does not exist"
      #         fi
      #     volumeMounts:
      #       - name: pg-hba-config
      #         mountPath: /config
      #       - name: postgres-storage
      #         mountPath: /var/lib/postgresql/data
      containers:
        - name: postgresql
          image: postgres:17.5
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_ADMIN_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_ADMIN_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_DATABASE
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          args: ["-c", "listen_addresses=*"]
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: axieanalytics-postgresql-pvc
        - name: pg-hba-config
          configMap:
            name: postgres-hba
      restartPolicy: Always
---
apiVersion: batch/v1
kind: Job
metadata:
  name: axieanalytics-postgresql-init
  namespace: axieanalytics
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: liquibase
          image: samlapointe01/axie-analytics:database-401
          command:
            - sh
            - -c
            - |
              export LIQUIBASE_COMMAND_URL="jdbc:postgresql://$PG_HOST:$PG_PORT/$PG_DATABASE" && \
              until pg_isready -h $PG_HOST -p $PG_PORT; do sleep 2; done && \
              liquibase --changelog-file=./changelogs/master.yaml update
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_HOST
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_PORT
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_ADMIN_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_ADMIN_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_DATABASE
            - name: store_sales_username
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_SALES_USERNAME
            - name: store_sales_password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_SALES_PASSWORD
            - name: store_axies_username
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_AXIES_USERNAME
            - name: store_axies_password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_AXIES_PASSWORD
            - name: backend_username
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: PG_BACKEND_USERNAME
            - name: backend_password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_BACKEND_PASSWORD