apiVersion: v1
kind: Service
metadata:
  name: axieanalytics-backend
  namespace: axieanalytics
spec:
  selector:
    app: axieanalytics-backend
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8000
    - protocol: TCP
      port: 443
      name: https
      targetPort: 8000
  type: ClusterIP